### ISSUE TITLE
Use case: Broadcast with late fanout

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-nv-use-cases#77]
A particular use case for WebRTC is real time media distribution (case 3.2).
One subset of this use case allows one participant in the distribution network to relay media to another participant in the network - for bandwidth sharing, for resilience, or to route around unreachable hops.

This brings with it requirements:

Nxx: A node must be able to forward media received from another node to a third node, with due respect to timing, content negotiation and congestion control.

**Comment by aboba** [comment]
Should we add an additional requirement for Section 3.2.2 (Low latency Broadcast)?  Today, the relays often handle containerized content (CMAF) with rendering handled via MSE. But if there is no need for DRM then containerization is unnecessary so that it would be desirable to support relaying of raw media over WebRTC, WebTransport, RTCDataChannel, etc.

Question: "is content negotiation" the requirement or is it "configuration"?  For example, WebCodecs allows configuration of the encoder or decoder but negotiation is handled outside of the API.

**Comment by alvestrand** [comment]
"content negotiation" was my shortform for "the outgoing PC may have negotiated different payload types from the incoming PC for the same codec" (and will certainly use a different SSRC).

3.2.2 seemed to focus on low latency from a central server directly to the end node, which is why I thought it best to formulate redistribution as a new use case.

**Comment by alvestrand** [comment]
If we merge #79 , I think we can close this issue as fixed.
