### ISSUE TITLE
Mobility backup candidate pairs

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-nv-use-cases#9]
Just to ensure we're talking about the same idea here: If both peers are behind a NAT, the backup candidate pair would most likely be relay-to-relay with both the clients and the TURN server supporting [TURN mobility](https://tools.ietf.org/html/rfc8016), correct? Because in that case, they could continue their connection without any signalling. (New host and srflx candidates could then be exchanged over a data channel.)

**Comment by aboba** [comment]
TURN mobility (RFC 8016) is typically used to quickly bring up a selected pair, while checking continues in the background.  If a better (e.g. less expensive) pair is found, the relay candidate can still be used as a backup to allow connectivity to be maintained when switching between interfaces.  The only wrinkle here is if an end-of-candidates indication is sent.

**Comment by aboba** [comment]
Within ICEbis (RFC 8445) a pair involving a relay candidate and TURN mobility ("backup pair") can be brought up right away while the search continues for a better candidate.  If the "better" candidate pair loses connectivity, the "backup pair" can be used instead.  This can be supported in both WebRTC 1.0 as well as in ORTC.  The issue is that after ICE nomination, non-selected candidates are pruned, so that the "backup pair" can no longer be assumed to be operational.  So the requested functionality essentially requires "continuous nomination", which is supported in ORTC lib.

**Comment by aboba** [comment]
Since both this issue and Issue https://github.com/w3c/webrtc-nv-use-cases/issues/10 related to "continuous nomination" (which has been implemented), I'm going to classify this issue as a duplicate.
