### ISSUE TITLE
N15 latency control should be formulated in a technology-agnostic way

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-nv-use-cases#91]
The current text of N15 is:

> The application must be able to control aspects of the data transport (e.g. set the SCTP heartbeat interval or turn it off), RTO values, etc.

This makes the assumption that 1) data transport is the only thing that needs controlling, and 2) that SCTP heartbeat and RTO are appropriate controls.

It should be restated in terms of what one wants to achieve, for instance:

> The application must be able to take steps to ensure a low and consistent latency for audio, video and data under varying network conditions. This may include tweaking of transport parameters for both media and data.

**Comment by aboba** [comment]
Agree that the requirement is more general.  There seems to be an implicit assumption that the browser is receiving media from the cloud and sending back game console input.  But it should also be possible for cloud gaming participants to send media to each other. 

My question is what API work is required to "ensure a low and consistent latency for audio, video and data".   One might argue WebRTC already attempts to achieve this for audio/video via congestion control algorithms such as gcc.  Since SCTP typically doesn't implement low-latency congestion control, there could be issues there.
